import Foundation

/// Reads a Telegram channel through its public web preview.
///
/// Telegram publishes no RSS and its Bot API cannot read a channel it was not
/// added to as an admin. What every channel with a public username *does* have
/// is `t.me/s/<channel>` — a plain server-rendered page of recent posts, no
/// account, no token, no JavaScript. Scraping that is the only route in, and it
/// is a stable one: the markup is generated by Telegram's own widget and the
/// class names have not moved in years.
///
/// It is still scraping, so everything here degrades rather than throws. A post
/// with no text still yields its photo and its link; a chunk that parses to
/// nothing is skipped and the rest of the page is kept.
enum TelegramFeed {

    /// Accepts a bare name, an @name, or any t.me URL and returns the name.
    ///
    /// People paste whichever of those is in their clipboard, and a source
    /// silently failing because the endpoint field holds a URL where a name was
    /// expected is a bad afternoon.
    static func normalizeChannel(_ raw: String) -> String {
        var text = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        for prefix in ["https://", "http://"] where text.lowercased().hasPrefix(prefix) {
            text.removeFirst(prefix.count)
        }
        for prefix in ["t.me/", "telegram.me/", "telegram.dog/"] where text.lowercased().hasPrefix(prefix) {
            text.removeFirst(prefix.count)
        }
        if text.lowercased().hasPrefix("s/") { text.removeFirst(2) }
        if text.hasPrefix("@") { text.removeFirst() }

        // Drop a post number or query string if one came along with the URL.
        if let slash = text.firstIndex(of: "/") { text = String(text[text.startIndex..<slash]) }
        if let question = text.firstIndex(of: "?") { text = String(text[text.startIndex..<question]) }
        return text
    }

    static func previewURL(for channel: String) -> URL? {
        let name = normalizeChannel(channel)
        guard !name.isEmpty,
              name.allSatisfy({ $0.isLetter || $0.isNumber || $0 == "_" }) else { return nil }
        return URL(string: "https://t.me/s/\(name)")
    }

    static func parse(html: String, channel: String, sourceID: String) -> [Article] {
        let name = normalizeChannel(channel)
        var articles: [Article] = []

        for chunk in messageChunks(in: html) {
            guard let article = article(from: chunk, channel: name, sourceID: sourceID) else { continue }
            articles.append(article)
        }
        return articles
    }

    // MARK: - Segmentation

    /// Splits the page into one substring per message.
    ///
    /// `data-post` is the anchor because it appears exactly once per message
    /// and carries the identity — `channel/1234` — that the article id needs.
    /// Slicing on the wrapper div instead would mean balancing several levels
    /// of nesting to find where each message ends.
    static func messageChunks(in html: String) -> [Substring] {
        var starts: [String.Index] = []
        var cursor = html.startIndex

        while let found = html.range(of: "data-post=\"", range: cursor..<html.endIndex) {
            starts.append(found.lowerBound)
            cursor = found.upperBound
        }
        guard !starts.isEmpty else { return [] }

        var chunks: [Substring] = []
        for (index, start) in starts.enumerated() {
            let end = index + 1 < starts.count ? starts[index + 1] : html.endIndex
            chunks.append(html[start..<end])
        }
        return chunks
    }

    private static func article(from chunk: Substring, channel: String, sourceID: String) -> Article? {
        guard let postID = attributeValue("data-post", in: chunk) else { return nil }

        let text = messageText(in: chunk)
        let image = imageURL(in: chunk)
        let video = videoURL(in: chunk)
        // The footer stamp is the message's own; anything earlier belongs to a
        // forward header or a reply preview.
        let published = FeedDate.parse(lastAttributeValue("datetime", in: chunk))

        // A post with neither words nor media is a service message —
        // "channel photo changed" — and not worth a row.
        guard !text.isEmpty || image != nil || video != nil else { return nil }

        let link = URL(string: "https://t.me/\(postID)")
        let body = text.isEmpty ? "(no caption)" : text

        return Article(
            id: sourceID + "|" + postID,
            sourceID: sourceID,
            // Telegram posts have no titles. Leaving this empty lets
            // `displayTitle` derive one, and keeps the row from printing the
            // same sentence as both headline and dek.
            title: "",
            summary: body,
            bodyHTML: nil,
            link: link,
            imageURL: image,
            videoURL: video,
            author: nil,
            published: published,
            context: "t.me/\(channel)"
        )
    }

    // MARK: - Fields

    /// The message body, with Telegram's inline markup flattened to text and its
    /// emoji removed.
    ///
    /// War channels open nearly every post with a wall of flags, sirens and
    /// red-circle emoji, and since a Telegram post has no title the app derives
    /// its headline from the first run of this text — so the emoji land exactly
    /// where the headline should be and every row reads as a pictogram before a
    /// word. Stripping them here cleans the derived headline and the dek in one
    /// place.
    private static func messageText(in chunk: Substring) -> String {
        // `js-message_text` and not `tgme_widget_message_text`: a reply preview
        // uses the second class with `js-message_reply_text`, and matching the
        // broad name pulls the quoted post in as if it were the post.
        guard let body = balancedDiv(in: chunk, classContaining: "js-message_text") else { return "" }
        return stripEmoji(from: HTMLText.plainText(from: String(body)))
    }

    /// Removes emoji and their joiners, then tidies the spacing they leave.
    ///
    /// Deliberately narrow: only pictographic scalars, the flag regional
    /// indicators, skin-tone modifiers, variation selectors and the
    /// zero-width joiner go. Digits, `#`, `*` and the like carry an emoji
    /// property too but are real text, so they are matched by explicit ranges
    /// rather than by the broad `isEmoji`, which would delete the "5" in "5
    /// killed".
    static func stripEmoji(from text: String) -> String {
        guard text.unicodeScalars.contains(where: isEmojiScalar) else { return text }
        var scalars = String.UnicodeScalarView()
        for scalar in text.unicodeScalars where !isEmojiScalar(scalar) {
            scalars.append(scalar)
        }
        // Emoji sat between words leave double spaces and stranded punctuation
        // ("🇮🇱 BREAKING:" → " BREAKING:"); collapse what is left.
        return HTMLText.collapseWhitespace(in: String(scalars))
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private static func isEmojiScalar(_ scalar: Unicode.Scalar) -> Bool {
        switch scalar.value {
        case 0x200D,                    // zero-width joiner
             0xFE00...0xFE0F,           // variation selectors
             0x1F1E6...0x1F1FF,         // regional indicators (flags)
             0x1F3FB...0x1F3FF,         // skin-tone modifiers
             0x2600...0x27BF,           // misc symbols, dingbats
             0x2B00...0x2BFF,           // misc symbols and arrows
             0x1F000...0x1FAFF,         // pictographs, emoticons, transport, supplemental
             0xE0020...0xE007F:         // tag characters (subdivision flags)
            return true
        default:
            // Anything else that is *drawn* as emoji by default — catches the
            // stragglers the ranges miss without touching ordinary text.
            return scalar.properties.isEmojiPresentation
        }
    }

    /// A photo or a video poster frame.
    ///
    /// Both are CSS background images rather than `<img>` tags, so the usual
    /// image extraction finds nothing on this page.
    private static func imageURL(in chunk: Substring) -> URL? {
        var remainder = chunk
        while let marker = remainder.range(of: "background-image:") {
            let rest = remainder[marker.upperBound...]
            guard let open = rest.range(of: "url(") else { break }
            let afterOpen = rest[open.upperBound...]
            guard let close = afterOpen.firstIndex(of: ")") else { break }

            var raw = String(afterOpen[afterOpen.startIndex..<close])
            raw = raw.trimmingCharacters(in: CharacterSet(charactersIn: "'\" "))
            let decoded = HTMLText.decodeEntities(in: raw)
            if decoded.hasPrefix("http"), let url = URL(string: decoded) { return url }

            remainder = rest[open.upperBound...]
        }
        return nil
    }

    /// The MP4 behind a video post.
    ///
    /// Telegram serves these as a plain file on its CDN with no signing and no
    /// token, which means a video post can actually play rather than bouncing
    /// out to a web page — and for a video post the video *is* the post, so
    /// bouncing out was losing the content entirely.
    ///
    /// Round video messages use the same tag, so both work.
    private static func videoURL(in chunk: Substring) -> URL? {
        var remainder = chunk
        while let open = remainder.range(of: "<video", options: .caseInsensitive) {
            guard let close = remainder[open.upperBound...].firstIndex(of: ">") else { return nil }
            let tag = remainder[open.upperBound..<close]

            if let raw = HTMLText.attributeValue("src", in: tag),
               raw.hasPrefix("http"),
               let url = URL(string: raw) {
                return url
            }
            remainder = remainder[remainder.index(after: close)...]
        }
        return nil
    }

    // MARK: - Small HTML helpers

    /// The contents of the first `<div>` whose class attribute contains
    /// `needle`, with nesting counted properly.
    ///
    /// Counting matters: Telegram wraps spoilers and quotes in their own divs,
    /// and stopping at the first `</div>` truncates any post containing one.
    static func balancedDiv(in html: Substring, classContaining needle: String) -> Substring? {
        var searchFrom = html.startIndex

        while let hit = html.range(of: needle, range: searchFrom..<html.endIndex) {
            searchFrom = hit.upperBound

            // Walk back to the `<` that opened the tag this class sits in, and
            // check it really is a div rather than, say, an anchor.
            guard let tagStart = html[html.startIndex..<hit.lowerBound].lastIndex(of: "<") else { continue }
            guard html[tagStart...].hasPrefix("<div") else { continue }
            guard let tagEnd = html[tagStart...].firstIndex(of: ">") else { return nil }

            let contentStart = html.index(after: tagEnd)
            var depth = 1
            var cursor = contentStart

            while cursor < html.endIndex, depth > 0 {
                guard let next = html.range(of: "<", range: cursor..<html.endIndex)?.lowerBound else {
                    return html[contentStart..<html.endIndex]
                }
                if html[next...].hasPrefix("</div") {
                    depth -= 1
                    if depth == 0 { return html[contentStart..<next] }
                    cursor = html.index(next, offsetBy: 5, limitedBy: html.endIndex) ?? html.endIndex
                } else if html[next...].hasPrefix("<div") {
                    depth += 1
                    cursor = html.index(next, offsetBy: 4, limitedBy: html.endIndex) ?? html.endIndex
                } else {
                    cursor = html.index(after: next)
                }
            }
            // Unbalanced: take what is there rather than dropping the post.
            return html[contentStart..<html.endIndex]
        }
        return nil
    }

    static func attributeValue(_ name: String, in html: Substring) -> String? {
        guard let open = html.range(of: "\(name)=\"") else { return nil }
        guard let close = html[open.upperBound...].firstIndex(of: "\"") else { return nil }
        let value = String(html[open.upperBound..<close])
        return value.isEmpty ? nil : HTMLText.decodeEntities(in: value)
    }

    static func lastAttributeValue(_ name: String, in html: Substring) -> String? {
        var result: String?
        var cursor = html.startIndex

        while let open = html.range(of: "\(name)=\"", range: cursor..<html.endIndex) {
            cursor = open.upperBound
            guard let close = html[open.upperBound...].firstIndex(of: "\"") else { break }
            let value = String(html[open.upperBound..<close])
            if !value.isEmpty { result = HTMLText.decodeEntities(in: value) }
        }
        return result
    }
}
