import Foundation

/// The terms the classifier scores against, and their weights.
///
/// **This file is parsed by `dispatch/tools/feed_reference.py`.** The tests for
/// the classifier read these tables directly out of the Swift rather than
/// keeping a second copy, so the lexicon cannot drift out of step with what is
/// tested. That means the shape has to stay mechanical: one `("term", weight),`
/// per line, nothing computed, no comments inside the array literals.
///
/// Weights, roughly:
///
///   3.0  decisive on its own — "airstrike" is not about anything else
///   2.0  strong, but a headline could pair it with another topic
///   1.0  suggestive; needs company to win
///   0.5  weak signal, mostly a tie-breaker
///
/// Multi-word entries are matched as phrases against the whole text, which is
/// what disambiguates the words that belong to two topics at once. "Strike" is
/// worth almost nothing alone, because a labour strike and an air strike are
/// different sections; "air strike" and "strike vote" are worth a lot each.
enum TopicLexicon {

    static let war: [(String, Double)] = [
        ("airstrike", 3.0),
        ("air strike", 3.0),
        ("air strikes", 3.0),
        ("missile strike", 3.0),
        ("drone strike", 3.0),
        ("missile", 2.5),
        ("missiles", 2.5),
        ("drone", 1.5),
        ("drones", 1.5),
        ("artillery", 3.0),
        ("shelling", 3.0),
        ("offensive", 1.5),
        ("counteroffensive", 3.0),
        ("frontline", 2.5),
        ("front line", 2.5),
        ("ceasefire", 3.0),
        ("truce", 2.5),
        ("troops", 2.5),
        ("soldiers", 2.0),
        ("infantry", 3.0),
        ("brigade", 2.5),
        ("battalion", 2.5),
        ("regiment", 2.0),
        ("insurgents", 2.5),
        ("militants", 2.5),
        ("militia", 2.5),
        ("warplane", 3.0),
        ("warplanes", 3.0),
        ("fighter jet", 3.0),
        ("fighter jets", 3.0),
        ("f-16", 2.5),
        ("f-35", 2.5),
        ("aircraft carrier", 3.0),
        ("destroyer", 1.5),
        ("frigate", 2.5),
        ("submarine", 2.0),
        ("warship", 3.0),
        ("warships", 3.0),
        ("nato", 2.0),
        ("pentagon", 2.0),
        ("centcom", 3.0),
        ("idf", 2.5),
        ("hezbollah", 3.0),
        ("hamas", 3.0),
        ("houthi", 3.0),
        ("houthis", 3.0),
        ("taliban", 2.5),
        ("isis", 2.5),
        ("wagner", 2.0),
        ("ukraine", 2.0),
        ("ukrainian", 2.0),
        ("kyiv", 2.5),
        ("kharkiv", 3.0),
        ("donetsk", 3.0),
        ("luhansk", 3.0),
        ("zaporizhzhia", 3.0),
        ("crimea", 2.5),
        ("gaza", 2.5),
        ("west bank", 2.5),
        ("rafah", 3.0),
        ("lebanon", 2.0),
        ("syria", 2.0),
        ("yemen", 2.0),
        ("red sea", 2.0),
        ("taiwan strait", 3.0),
        ("south china sea", 3.0),
        ("invasion", 2.5),
        ("incursion", 2.5),
        ("airspace", 2.0),
        ("no-fly zone", 3.0),
        ("air defense", 3.0),
        ("air defence", 3.0),
        ("patriot battery", 3.0),
        ("himars", 3.0),
        ("javelin", 2.0),
        ("casualties", 2.5),
        ("killed in action", 3.0),
        ("war crimes", 2.5),
        ("mobilization", 2.0),
        ("conscription", 2.5),
        ("nuclear weapon", 2.5),
        ("warhead", 3.0),
        ("ballistic", 2.5),
        ("hypersonic", 3.0),
        ("cruise missile", 3.0),
        ("interceptor", 2.0),
        ("bombardment", 3.0),
        ("bombing", 2.5),
        ("siege", 2.5),
        ("military aid", 2.5),
        ("arms package", 2.5),
        ("deployment", 1.5),
        ("occupation", 1.5),
        ("guerrilla", 2.5),
        ("paramilitary", 2.5),
        ("mercenaries", 2.5),
        ("prisoner exchange", 2.5),
        ("hostage", 2.0),
        ("terror attack", 2.5),
        ("combat", 2.0),
        ("battlefield", 3.0),
        ("war", 1.5),
        ("wartime", 2.0),
        ("strike package", 3.0),
        ("special operations", 2.5),
        ("recon", 1.5),
        ("intercepted", 1.5),
        ("radar", 1.5),
        ("stealth bomber", 3.0),
        ("b-2", 2.0),
        ("b-21", 2.5),
        ("submarine-launched", 3.0),
        ("carrier strike group", 3.0),
        ("strike group", 3.0),
        ("air base", 3.0),
        ("airbase", 3.0),
        ("military base", 2.5),
        ("air raid", 3.0),
        ("iron dome", 3.0),
        ("irgc", 3.0),
        ("quds force", 3.0),
        ("manpads", 3.0),
        ("explosion", 1.5),
        ("explosions", 1.5),
        ("shrapnel", 3.0),
        ("mortar", 2.5),
        ("shelled", 3.0),
        ("shot down", 2.5),
        ("scrambled jets", 3.0),
        ("air raid sirens", 3.0),
        ("anti-ship", 3.0),
        ("nuclear test", 3.0),
        ("proxy forces", 2.5),
        ("arms shipment", 2.5),
    ]

    static let politics: [(String, Double)] = [
        ("election", 2.5),
        ("elections", 2.5),
        ("primary election", 3.0),
        ("ballot", 2.5),
        ("voters", 2.5),
        ("voter", 2.0),
        ("turnout", 2.0),
        ("polling", 1.5),
        ("poll numbers", 2.5),
        ("campaign trail", 3.0),
        ("candidate", 2.0),
        ("nominee", 2.5),
        ("congress", 2.5),
        ("senate", 2.5),
        ("senator", 2.5),
        ("house republicans", 3.0),
        ("house democrats", 3.0),
        ("congressman", 2.5),
        ("congresswoman", 2.5),
        ("lawmakers", 2.5),
        ("legislation", 2.0),
        ("bill passed", 2.5),
        ("filibuster", 3.0),
        ("impeachment", 3.0),
        ("subpoena", 2.5),
        ("indictment", 2.5),
        ("grand jury", 2.5),
        ("supreme court", 2.5),
        ("scotus", 3.0),
        ("appeals court", 2.5),
        ("federal judge", 2.5),
        ("attorney general", 2.5),
        ("doj", 2.0),
        ("fbi", 2.0),
        ("white house", 2.5),
        ("oval office", 3.0),
        ("executive order", 3.0),
        ("veto", 2.5),
        ("cabinet", 2.0),
        ("governor", 2.0),
        ("mayor", 1.5),
        ("republican", 2.0),
        ("democrat", 2.0),
        ("democrats", 2.0),
        ("republicans", 2.0),
        ("gop", 2.5),
        ("bipartisan", 2.5),
        ("partisan", 2.0),
        ("caucus", 2.5),
        ("committee hearing", 2.5),
        ("testimony", 1.5),
        ("whistleblower", 2.0),
        ("immigration", 2.0),
        ("border policy", 2.5),
        ("deportation", 2.5),
        ("asylum", 2.0),
        ("abortion", 2.5),
        ("gun control", 2.5),
        ("second amendment", 2.5),
        ("first amendment", 2.5),
        ("censorship", 2.0),
        ("free speech", 2.0),
        ("lobbying", 2.5),
        ("super pac", 3.0),
        ("approval rating", 2.5),
        ("state of the union", 3.0),
        ("press secretary", 3.0),
        ("referendum", 2.5),
        ("parliament", 2.5),
        ("prime minister", 2.0),
        ("chancellor", 1.5),
        ("coalition government", 3.0),
        ("no confidence", 2.5),
        ("political", 1.5),
        ("politician", 2.0),
        ("policy", 1.0),
        ("scandal", 1.5),
        ("corruption", 1.5),
        ("protest", 1.5),
        ("protests", 1.5),
        ("campaign rally", 3.0),
        ("court ruling", 2.0),
        ("lawsuit", 1.5),
        ("investigation", 1.0),
        ("resignation", 1.5),
        ("appointed", 1.0),
        ("confirmation hearing", 3.0),
        ("impeach", 3.0),
        ("midterms", 3.0),
        ("swing state", 3.0),
        ("electoral college", 3.0),
        ("recount", 3.0),
        ("pardon", 2.5),
        ("vice president", 2.0),
        ("congressional", 2.0),
        ("state department", 1.5),
        ("border patrol", 2.5),
        ("sanctuary city", 2.5),
        ("voter fraud", 3.0),
        ("mail-in ballots", 3.0),
        ("gerrymander", 3.0),
        ("nominated", 1.5),
        ("sworn in", 2.5),
    ]

    static let economics: [(String, Double)] = [
        ("inflation", 3.0),
        ("cpi", 3.0),
        ("ppi", 2.5),
        ("consumer price", 3.0),
        ("interest rate", 3.0),
        ("interest rates", 3.0),
        ("rate cut", 3.0),
        ("rate hike", 3.0),
        ("basis points", 3.0),
        ("federal reserve", 3.0),
        ("the fed", 2.5),
        ("fomc", 3.0),
        ("powell", 2.5),
        ("central bank", 3.0),
        ("ecb", 2.5),
        ("bank of japan", 3.0),
        ("treasury yield", 3.0),
        ("yields", 2.5),
        ("bond market", 3.0),
        ("bonds", 2.0),
        ("10-year", 2.5),
        ("yield curve", 3.0),
        ("recession", 3.0),
        ("gdp", 3.0),
        ("unemployment", 3.0),
        ("jobless claims", 3.0),
        ("payrolls", 3.0),
        ("nonfarm", 3.0),
        ("labor market", 2.5),
        ("wage growth", 2.5),
        ("stocks", 2.5),
        ("stock market", 3.0),
        ("equities", 3.0),
        ("s&p 500", 3.0),
        ("nasdaq", 3.0),
        ("dow jones", 3.0),
        ("russell 2000", 3.0),
        ("vix", 2.5),
        ("futures", 2.0),
        ("earnings", 2.5),
        ("revenue", 2.0),
        ("guidance", 1.5),
        ("quarterly results", 3.0),
        ("ipo", 2.5),
        ("buyback", 2.5),
        ("dividend", 2.5),
        ("valuation", 2.5),
        ("market cap", 2.5),
        ("bitcoin", 3.0),
        ("btc", 2.5),
        ("ethereum", 3.0),
        ("crypto", 2.5),
        ("stablecoin", 3.0),
        ("gold price", 3.0),
        ("silver price", 3.0),
        ("crude oil", 3.0),
        ("wti", 3.0),
        ("brent", 2.5),
        ("opec", 3.0),
        ("natural gas", 2.5),
        ("commodities", 2.5),
        ("dollar index", 3.0),
        ("dxy", 3.0),
        ("currency", 2.0),
        ("forex", 3.0),
        ("yuan", 2.0),
        ("tariff", 2.5),
        ("tariffs", 2.5),
        ("trade deficit", 3.0),
        ("supply chain", 2.5),
        ("housing market", 3.0),
        ("mortgage rate", 3.0),
        ("home sales", 2.5),
        ("retail sales", 3.0),
        ("consumer confidence", 3.0),
        ("bankruptcy", 2.5),
        ("default", 2.0),
        ("debt ceiling", 2.5),
        ("national debt", 2.5),
        ("deficit", 2.0),
        ("liquidity", 2.5),
        ("quantitative easing", 3.0),
        ("balance sheet", 2.0),
        ("credit market", 3.0),
        ("bank failure", 3.0),
        ("hedge fund", 2.5),
        ("private equity", 2.5),
        ("layoffs", 2.5),
        ("job cuts", 2.5),
        ("strike vote", 2.5),
        ("labor strike", 3.0),
        ("authorize strike", 3.0),
        ("strike authorization", 3.0),
        ("walkout", 2.5),
        ("picket line", 3.0),
        ("collective bargaining", 3.0),
        ("labor union", 2.5),
        ("union workers", 2.5),
        ("teamsters", 2.5),
        ("uaw", 2.5),
        ("autoworkers", 2.5),
        ("economy", 2.0),
        ("economic", 2.0),
        ("investors", 2.0),
        ("rally", 1.0),
        ("selloff", 2.5),
        ("bear market", 3.0),
        ("bull market", 3.0),
        ("correction", 1.0),
        ("volatility", 2.0),
        ("gold", 1.5),
        ("oil price", 3.0),
        ("oil prices", 3.0),
        ("gas prices", 3.0),
        ("gasoline", 2.5),
        ("wall street", 2.5),
        ("jobs report", 3.0),
        ("core inflation", 3.0),
        ("pce", 2.5),
        ("rate decision", 3.0),
        ("bond yields", 3.0),
        ("cost of living", 3.0),
        ("grocery prices", 3.0),
        ("egg prices", 3.0),
        ("minimum wage", 2.5),
        ("foreclosure", 2.5),
        ("insolvency", 2.5),
        ("credit card debt", 2.5),
        ("consumer spending", 2.5),
        ("trade war", 2.0),
        ("money supply", 2.5),
        ("real wages", 2.5),
    ]
}
