#!/usr/bin/env python3
"""Generate the Android lexicon from the iOS one.

Five hundred weighted terms maintained in two languages would diverge inside a
week, and the divergence would be invisible: both apps would keep working and
quietly file the same story differently. So `TopicLexicon.swift` is the single
source and this writes the Kotlin.

The Python test suite already parses the Swift directly for the same reason.
That makes three consumers of one table, which is the point.

Run: python3 dispatch/tools/gen_lexicon_kt.py
`precheck.py` runs it with --check and fails if the generated file is stale.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)

sys.path.insert(0, HERE)
from feed_reference import load_lexicon  # noqa: E402

TARGET = os.path.join(REPO, "android", "core", "src", "main", "kotlin",
                      "com", "nurtrino", "dispatch", "core", "TopicLexicon.kt")

HEADER = '''package com.nurtrino.dispatch.core

// Generated by dispatch/tools/gen_lexicon_kt.py from
// ios/Dispatch/Net/TopicLexicon.swift. Do not edit by hand: edit the Swift and
// re-run the generator, or the two apps will file the same story differently and
// nothing will tell you.
//
// Weights, roughly:
//
//   3.0  decisive on its own
//   2.0  strong, but a headline could pair it with another topic
//   1.0  suggestive; needs company to win
//  -2.0  cancels: this phrase is the *other* sense of a term above it
object TopicLexicon {
'''


def render():
    tables = load_lexicon()
    out = [HEADER]
    for topic in ("war", "politics", "economics"):
        out.append("\n    val %s: List<Pair<String, Double>> = listOf(\n" % topic)
        for term, weight in tables[topic]:
            out.append('        "%s" to %s,\n' % (term, weight))
        out.append("    )\n")
    out.append("}\n")
    return "".join(out)


def main():
    body = render()
    check = "--check" in sys.argv

    existing = None
    if os.path.exists(TARGET):
        with open(TARGET, encoding="utf-8") as handle:
            existing = handle.read()

    if check:
        if existing != body:
            print("FAIL: TopicLexicon.kt is stale — run tools/gen_lexicon_kt.py")
            raise SystemExit(1)
        print("TopicLexicon.kt is current")
        return

    os.makedirs(os.path.dirname(TARGET), exist_ok=True)
    with open(TARGET, "w", encoding="utf-8") as handle:
        handle.write(body)
    terms = sum(len(table) for table in load_lexicon().values())
    print("wrote TopicLexicon.kt  %d terms" % terms)


if __name__ == "__main__":
    main()
